### ISSUE TITLE
[ERROR] - dbus: unsupported cursor mode requested, ignoring

### ISSUE THREAD

**Issue by Zedo9** [hyprwm/xdg-desktop-portal-hyprland#45]
I'm getting the following error every time I try to do a screen share using `brave-bin 1:1.50.114-1` (Or `ungoogled-chromium 112.0.5615.49-1`) and it is failing.

Output from `systemctl --user status xdg-desktop-portal-hyprland`

```sh
/04/13 20:29:53 [ERROR] - dbus: unsupported cursor mode requested, ignoring
xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-hyprland.service; static)
     Active: active (running) since Thu 2023-04-13 20:29:29 CET; 9min ago
   Main PID: 1057 (xdg-desktop-por)
      Tasks: 6 (limit: 37710)
     Memory: 30.3M
        CPU: 1.283s
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/xdg-desktop-portal-hyprland.service
             └─1057 /usr/lib/xdg-desktop-portal-hyprland

Apr 13 20:29:29 archpad systemd[565]: Starting Portal service (Hyprland implementation)...
Apr 13 20:29:29 archpad systemd[565]: Started Portal service (Hyprland implementation).
Apr 13 20:29:53 archpad xdg-desktop-portal-hyprland[1057]: 2023/04/13 20:29:53 [ERROR] - dbus: unsupported cursor mode requested, ignoring
Apr 13 20:30:00 archpad xdg-desktop-portal-hyprland[1057]: 2023/04/13 20:30:00 [ERROR] - dbus: unsupported cursor mode requested, ignoring
```

Output from `systemctl --user status xdg-desktop-portal`

```sh
xdg-desktop-portal.service - Portal service
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal.service; static)
     Active: active (running) since Thu 2023-04-13 20:29:29 CET; 13min ago
   Main PID: 1018 (xdg-desktop-por)
      Tasks: 5 (limit: 37710)
     Memory: 10.1M
        CPU: 192ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/xdg-desktop-portal.service
             └─1018 /usr/lib/xdg-desktop-portal

Apr 13 20:29:29 archpad systemd[565]: Starting Portal service...
Apr 13 20:29:29 archpad xdg-desktop-por[1018]: No skeleton to export
Apr 13 20:29:29 archpad systemd[565]: Started Portal service.
```

**Note that everything works correctly on Firefox.**

# Environment

```
System:
Kernel: 6.2.10-arch1-1 
arch: x86_64 bits: 64 
Desktop: Hyprland
Distro: Arch Linux

CPU:
Info: 8-core 
model: AMD Ryzen 7 4800H with Radeon Graphics 
bits: 64

Graphics:
  Device-1: AMD Renoir driver: amdgpu v: kernel
  Device-2: Chicony Integrated Camera type: USB driver: uvcvideo
  Display: wayland server: X.Org v: 23.1.1 with: Xwayland v: 23.1.1
    compositor: Hyprland driver: X: loaded: amdgpu unloaded: modesetting,vesa
    dri: radeonsi gpu: amdgpu resolution: 1536x864~120Hz
  API: OpenGL v: 4.6 Mesa 23.0.2 renderer: AMD Radeon Graphics (renoir LLVM
    15.0.7 DRM 3.49 6.2.10-arch1-1)
```

```sh
# ~./.config/brave-flags.conf

--ozone-platform-hint=auto
```

```sh
# ~/.config/hypr/Hyprland.conf

monitor = ,preferred,auto,1.25

env = TERMINAL,alacritty
env = VISUAL,nvim
env = EDITOR,nvim
env = BROWSER,firefox

env = SDL_VIDEODRIVER,wayland
env = GDK_BACKEND,wayland,x11
env = MOZ_ENABLE_WAYLAND,1
env = XCURSOR_SIZE,24
env = _JAVA_AWT_WM_NONREPARENTING,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

...

# Autostart
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = wlr-wallpaper 
exec-once = xsettingsd &
exec-once = waybar -c ~/.config/waybar/config.hyprland
exec-once = easyeffects --gapplication-service
exec-once = dunst
exec-once = wlr-night-light
exec-once = wl-paste --watch cliphist store
exec-once = nm-applet --indicator
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = keyring # Gnome keyring
```

# Things I have already checked

- WebRTC PipeWire support is enabled in `chrome://flags`
- The browser is running on wayland natively.
- I have `xdg-desktop-portal 1.16.0-1` and `xdg-desktop-portal-hyprland-git 1:r261.e1f145d-4` installed with no other portal implementations.

**Comment by vaxerski** [comment]
it was a needed band-aid for #39 but tbh I should probably revert it. It's doing more harm than good.

**Comment by vaxerski** [comment]
should be fixed in 2366b4d415900b72c4001770ed8456bcfff569f4

**Comment by Zedo9** [comment]
It looks like it's not the real issue, I just installed the `xdg-desktop-portal-hyprland 0.2.1-1` from the community repository and replaced the old one and it didn't happen now.. However, screen sharing still doesn't work :thinking:

**Comment by vaxerski** [comment]
yeah that black screen is unrelated to the error.

Does the picker pop up?

**Comment by Zedo9** [comment]
It does

[output.webm](https://user-images.githubusercontent.com/48986303/231877841-05fbeb6b-1c22-4e1d-8d58-b9c147e0f427.webm)

**Comment by vaxerski** [comment]
really odd. What about obs / firefox?

**Comment by vaxerski** [comment]
lmfao common chrome L

**Comment by vaxerski** [comment]
got fixed in head

**Comment by tristanbeedell** [comment]
Same as described by @Zedo9 and shown in the screencasts. I am not able to share my screen in brave, but obs and firefox work. The GUM test shows 'success', but a blank screen. journalctl shows 'unsupported cursor mode requested'

**Comment by tristanbeedell** [comment]
Ok, so to be clear, this is a problem with Chromium. I can now confirm that sharing works on the latest Brave Nightly 1.52.54, Chromium 112.0.5615.121.

Thank you!
